name: riskanalysis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.13.1  # Added for app icon
  animate_do: ^3.3.4  # Added for animations
  lottie: ^3.1.0  # Added for Lottie animations

  # Security & Authentication
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  email_validator: ^3.0.0
  firebase_database: ^11.1.4
  local_auth: ^2.3.0

  # Data Handling & Storage
  sqflite: ^2.4.0
  path_provider: ^2.1.2
  root_access: ^1.0.4
  shared_preferences: ^2.3.2
  hive: ^2.2.3  # Added for local storage
  hive_flutter: ^1.1.0  # Added for Hive Flutter integration

  # Charts and Graphs
  fl_chart: ^0.66.2
  syncfusion_flutter_charts: ^27.1.56

  # Network & API
  http: ^1.2.0
  dio: ^5.4.1
  connectivity_plus: ^5.0.2  # Added for network connectivity

  # Device Info & Permissions
  device_info_plus: ^9.1.1
  network_info_plus: ^4.1.0
  permission_handler: ^11.3.0
   # Added for app info

  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  image_picker: ^1.0.7  # Added for image picking
  file_picker: ^6.1.1  # Added for file picking
  share_plus: ^7.2.1  # Added for sharing content

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  # Background color for Android adaptive icon
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"  # Foreground image for Android adaptive icon
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
   # Added for Lottie animations
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600