// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxIlnkbdagSVxlBo9afk9CJAL2oFmGACk',
    appId: '1:876986450363:web:2e9490bcae43f0ac4c449e',
    messagingSenderId: '876986450363',
    projectId: 'risk-anlysis',
    authDomain: 'risk-anlysis.firebaseapp.com',
    storageBucket: 'risk-anlysis.appspot.com',
    measurementId: 'G-S7WF8QTNG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvFDthdIGItIJEozQQG6SoVJ1IOJis7k',
    appId: '1:876986450363:android:9c179a49492a25344c449e',
    messagingSenderId: '876986450363',
    projectId: 'risk-anlysis',
    storageBucket: 'risk-anlysis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_ntPOIT9kaab7kJfXLxaSnvpQzT9awc',
    appId: '1:876986450363:ios:7aa8630796522e044c449e',
    messagingSenderId: '876986450363',
    projectId: 'risk-anlysis',
    storageBucket: 'risk-anlysis.appspot.com',
    iosBundleId: 'com.example.riskanalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_ntPOIT9kaab7kJfXLxaSnvpQzT9awc',
    appId: '1:876986450363:ios:7aa8630796522e044c449e',
    messagingSenderId: '876986450363',
    projectId: 'risk-anlysis',
    storageBucket: 'risk-anlysis.appspot.com',
    iosBundleId: 'com.example.riskanalysis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxIlnkbdagSVxlBo9afk9CJAL2oFmGACk',
    appId: '1:876986450363:web:1af7978fe8c82ee04c449e',
    messagingSenderId: '876986450363',
    projectId: 'risk-anlysis',
    authDomain: 'risk-anlysis.firebaseapp.com',
    storageBucket: 'risk-anlysis.appspot.com',
    measurementId: 'G-WH97BHW7V7',
  );
}
